### ISSUE TITLE
Add memcache to Loki for better performance

### ISSUE THREAD

**Issue by Mirio** [brucellino/nomad-jobs#98]
Hi Bruce,
After many scenarios test I suggest you to implement memcache on top of Loki to have a smoother experience.
You can find some information about it here [https://grafana.com/docs/loki/latest/operations/caching/](https://grafana.com/docs/loki/latest/operations/caching/).
If you need any help feel free to ask.
Ciao

**Comment by brucellino** [comment]
Sounds like a great idea... Loki is deployed in monolith mode at the moment (I'm not too worried about performance, just that it works), but perhaps it's time to start learning the finer details. If you'd like to send even a partial PR, we can hack it together.

**Comment by Mirio** [comment]
I've pushed the PR #99, It adds memcached nomad job.

**Comment by brucellino** [comment]
Closed by #99
